on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          path: 'testrepo'
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          zip -r testrepo.zip testrepo/
      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
      
      - name: Install dependencies with composer
        run: cd testrepo; composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Install dependencies with composer
        env:
            API_SECRET: ${{ secrets.API_SECRET }}
        run: |
          curl -vv \
          -F "key=$API_SECRET" \
          -X POST \
          -F "ModuleVersionUpload[zipFile]=@testrepo.zip" \
          https://api.humhub.com/v1/marketplace/upload?moduleId=testrepo
          