on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          path: 'testrepo'

      - name: Build project
        run: |
          zip -r testrepo.zip testrepo/
      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
      
      - name: Install Composer
        run: cd testrepo; composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Install NPM
        run: cd testrepo; npm install

      - name: Upload Package to HumHub
        run: |
          curl -v --fail-with-body \
          -F "key=${{secrets.API_KEY}}" \
          -F "ModuleVersionUpload[zipFile]=@testrepo.zip" \
          https://api.humhub.com/v1/marketplace/upload?moduleId=testrepo
